version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: game-of-life-backend
    environment:
      - CORS_ORIGINS=http://localhost:80,http://frontend:80
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - game-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - SKIP_HUSKY=1
    container_name: game-of-life-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
      - SKIP_HUSKY=1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - game-network

networks:
  game-network:
    name: game-network
    driver: bridge

volumes:
  backend-data:
    name: game-of-life-backend-data
